name: Post Etsy RSS to Pinterest

on:
  workflow_dispatch:
    inputs:
      post_limit:
        description: 'How many pins would you like to post?'
        required: true
        default: '1'

permissions:
  contents: write

jobs:
  post-to-pinterest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pinterest Posting Script
        env:
          PINTEREST_PIN_ACCESS_TOKEN: ${{ secrets.PINTEREST_PIN_ACCESS_TOKEN }}
          PINTEREST_BOARD_ACCESS_TOKEN: ${{ secrets.PINTEREST_BOARD_ACCESS_TOKEN }}
        run: python post_to_pinterest.py ${{ github.event.inputs.post_limit }}

      - name: Commit last_posted_pinterest.txt
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_posted_pinterest.txt
          git commit -m 'Update last posted Pinterest link' || echo "No changes to commit"
          git push
