name: Post Etsy RSS to Facebook Page

on:
  workflow_dispatch: # manual run option
  
permissions:
  contents: write

jobs:
  post-to-facebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Post Script
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          FB_PAGE_ACCESS_TOKEN : ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
        run: python post_to_facebook.py

      - name: Commit last_posted.txt
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_posted_facebook.txt
          git commit -m 'Update last posted link' || echo "No changes to commit"
          git push
